
/* Partie 4*/

SELECT MODELE,MARQUE FROM MODELE Md , MARQUE Mr WHERE Md.NUMMARQUE = Mr.NUMMARQUE;
\
SELECT * FROM VEHICULE WHERE NUMVEHICULE IN (SELECT NUMVEHICULE FROM INTERVENTIONS);
\
SELECT AVG(DATEFININTERV - DATEDEBINTERV) FROM INTERVENTIONS;
\
SELECT SUM(COUTINTERV) FROM INTERVENTIONS WHERE COUTINTERV >= 30000;
\
SELECT * FROM EMPLOYE WHERE NUMEMPLOYE IN (SELECT MAX(count(*)) FROM INTERVENTIONS GROUP BY NUMEMPLOYE)
