/***********/
/*  TYPES  */
/***********/
	CREATE OR REPLACE TYPE THotel AS OBJECT(
		NUMHOTEL INTEGER,
		NOMHOTEL VARCHAR2(50),
		VILLE VARCHAR2(50),
		ETOILES INTEGER,

		MEMBER FUNCTION nbChambre RETURN INTEGER,
		MEMBER FUNCTION nbEvaluationDate(DateE Date) RETURN INTEGER
	);
	/

	CREATE OR REPLACE TYPE TChambre AS OBJECT(
		NUMCHAMBRE INTEGER,
		NUMHOTEL INTEGER,
		ETAGE INTEGER,
		TYPECHAMBRE VARCHAR2(50),
		PRIXNUIT INTEGER,

		MEMBER FUNCTION chiffreAffaire RETURN INTEGER
	);
	/

	CREATE OR REPLACE TYPE TCLIENT AS OBJECT(
		NUMCLIENT INTEGER,
		NOMCLIENT VARCHAR(50),
		PRENOMCLIENT VARCHAR(50),
		EMAIL VARCHAR(50),

		MEMBER FUNCTION nbReservation RETURN INTEGER
	);
	/

	CREATE OR REPLACE TYPE TRESERVATION AS OBJECT(
		NUMCLIENT INTEGER,
		NUMHOTEL INTEGER,
		DATEARRIVEE DATE,
		DATEDEPART DATE,
		NUMCHAMBRE INTEGER
	);
	/
	CREATE OR REPLACE TYPE TEVALUATION AS OBJECT(
		NUMHOTEL INTEGER,
		NUMCLIENT INTEGER,
		DATEev DATE,
		NOTE INTEGER
	);
	/
/***********/
/* Methods */
/***********/
	CREATE OR REPLACE TYPE BODY TCLIENT
	AS
		MEMBER FUNCTION nbReservation RETURN INTEGER IS
			compt INTEGER :=0;
		BEGIN
		    
		    SELECT COUNT(*) INTO compt
		    FROM RESERVATION
		    WHERE NUMCLIENT = self.NUMCLIENT;
		    
		    RETURN compt;
		END ;
	END;
	/
	CREATE OR REPLACE TYPE BODY THotel
	AS
		MEMBER FUNCTION nbChambre RETURN INTEGER IS
			compt INTEGER :=0;
		BEGIN
		    
		    SELECT COUNT(*) INTO compt
		    FROM Chambre
		    WHERE NUMHOTEL = self.NUMHOTEL;
		    
		    RETURN compt;
		END;
		MEMBER FUNCTION nbEvaluationDate(DateE Date) RETURN INTEGER 
		IS
			compt INTEGER :=0;
		BEGIN
		    
		    SELECT COUNT(*) INTO compt
		    FROM EVALUATION
		    WHERE NUMHOTEL = self.NUMHOTEL AND DATEev = DateE;
		    
		    RETURN compt;
		END ;
	END;
	/
	CREATE OR REPLACE TYPE BODY TChambre
	AS
		MEMBER FUNCTION chiffreAffaire RETURN INTEGER IS
			compt INTEGER :=0;
		BEGIN
		    
		    SELECT PRIXNUIT*COUNT(*) INTO compt
		    FROM CHAMBRE ch,RESERVATION rs
		    WHERE ch.NUMCHAMBRE = self.NUMCHAMBRE AND ch.NUMCHAMBRE = rs.NUMCHAMBRE
		    GROUP BY ch.NUMCHAMBRE;
		    
		    RETURN compt;
		END ;
	END;
	/

/***********/
/* TABLES  */
/***********/
	CREATE TABLE Hotel OF THotel(
		CONSTRAINT PK_H PRIMARY KEY (NUMHOTEL),
		CONSTRAINT CH_Etoile CHECK (ETOILES BETWEEN 1 AND 5)
	);
	/
	CREATE TABLE Chambre OF TChambre(
		CONSTRAINT FK_chHotel FOREIGN KEY (NUMHOTEL) REFERENCES Hotel(NUMHOTEL),
		CONSTRAINT PK_CH PRIMARY KEY (NUMCHAMBRE , NUMHOTEL), 
		CONSTRAINT CH_TypeChambre CHECK (TYPECHAMBRE IN ('simple', 'double', 'triple','suite','autre'))
	);
	/
	CREATE TABLE  CLIENT OF TCLIENT(
		CONSTRAINT PK_CLIENT PRIMARY KEY (NUMCLIENT)
	);
	/
	CREATE TABLE RESERVATION OF TRESERVATION(
		CONSTRAINT FK_resClient FOREIGN KEY (NUMCLIENT) REFERENCES CLIENT(NUMCLIENT),
		CONSTRAINT FK_resNUMCHAMBRE FOREIGN KEY (NUMHOTEL,NUMCHAMBRE) REFERENCES Chambre(NUMHOTEL,NUMCHAMBRE),
		CONSTRAINT PK_RESERVATION PRIMARY KEY (NUMHOTEL,NUMCLIENT,DATEARRIVEE),
		CONSTRAINT CHECK_DATES CHECK ( DATEDEPART > DATEARRIVEE)
	);
	/
	CREATE TABLE EVALUATION OF TEVALUATION(
		CONSTRAINT FK_evClient FOREIGN KEY (NUMCLIENT) REFERENCES CLIENT(NUMCLIENT),
		CONSTRAINT FK_evHOTEL FOREIGN KEY (NUMHOTEL) REFERENCES Hotel(NUMHOTEL),
		CONSTRAINT CH_NOTE CHECK (NOTE BETWEEN 1 AND 10)
	);
	/


/***********/
/*Fonction */
/***********/

/*9*/SELECT NOMHOTEL,VILLE FROM HOTEL;

/*10*/SELECT NOMHOTEL FROM HOTEL WHERE NUMHOTEL IN(SELECT NUMHOTEL FROM RESERVATION);

/*11*/SELECT NOMCLIENT FROM CLIENT WHERE NUMCLIENT IN(
	SELECT NUMCLIENT FROM RESERVATION WHERE (NUMCHAMBRE,NUMHOTEL) IN (
		SELECT NUMCHAMBRE,NUMHOTEL FROM CHAMBRE WHERE ETAGE =1
		)
)

/*12*/SELECT NOMHOTEL,VILLE,PRIXNUIT FROM HOTEL ht,CHAMBRE ch WHERE ch.NUMHOTEL = ht.NUMHOTEL AND ch.TYPECHAMBRE ='suite';

/*13*/
	SELECT NOMHOTEL,max(nombre_reservation) as nombre_reservation ,max(TYPECHAMBRE) as TYPECHAMBRE FROM(
			SELECT h.NOMHOTEL,ch.TYPECHAMBRE,ch.NUMHOTEL,count(*) as nombre_reservation FROM RESERVATION  rs,CHAMBRE ch,HOTEL h 
			WHERE rs.NUMHOTEL =  ch.NUMHOTEL AND rs.NUMCHAMBRE = ch.NUMCHAMBRE AND ch.NUMHOTEL = h.NUMHOTEL AND LOWER(h.VILLE)='alger' GROUP BY  ch.TYPECHAMBRE,ch.NUMHOTEL,h.NOMHOTEL
		)GROUP BY NOMHOTEL



/*14*/SELECT NOMHOTEL,VILLE FROM HOTEL WHERE NUMHOTEL IN (
	SELECT NUMHOTEL FROM EVALUATION WHERE EXTRACT(YEAR FROM DATEev)=2022 GROUP BY NUMHOTEL HAVING avg(NOTE) >= 0
)

/*15*/
/*AND EXTRACT(MONTH FROM res.DATEARRIVEE) >= 06 AND EXTRACT(MONTH FROM res.DATEDEPART) <= 8*/
	SELECT NOMHOTEL,max(CA) as max_chiffreAffaire FROM
	(SELECT NOMHOTEL,sum(chiffreAffaire) as CA  FROM (
		select h.NOMHOTEL,ch.PRIXNUIT*count(*) as chiffreAffaire FROM HOTEL h,CHAMBRE ch,RESERVATION res 
		WHERE res.NUMHOTEL = ch.NUMHOTEL  AND res.NUMCHAMBRE = ch.NUMCHAMBRE AND h.NUMHOTEL = ch.NUMHOTEL 
		GROUP BY  h.NOMHOTEL,ch.PRIXNUIT
			) GROUP BY  NOMHOTEL
		ORDER BY CA DESC
	)WHERE ROWNUM <= 1 GROUP BY NOMHOTEL;
	




/***********/
/*  DROP   */
/***********/

DROP TABLE RESERVATION;
/
DROP TABLE EVALUATION;
/
DROP TABLE CLIENT;
/
DROP TABLE CHAMBRE;
/
DROP TABLE HOTEL;
/
DROP TYPE THotel;
/
DROP TYPE TEVALUATION;
/
DROP TYPE TCLIENT;
/
DROP TYPE TCHAMBRE;
/
DROP TYPE TRESERVATION;
/

/***********/
/*  UTILS   */
/***********/
	SELECT OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TYPE' or OBJECT_TYPE = 'TABLE';
	SELECT * FROM all_USER_METHODS WHERE TYPE_NAME = 'Client';