CREATE TABLESPACE Intervention_tbs DATAFILE '/Intervention_tbs.dat' AUTOEXTEND ON ONLINE;
CREATE TEMPORARY TABLESPACE Intervention_temptbs DATAFILE '/Intervention_temptbs.dat' SIZE 100M AUTOEXTEND ON ONLINE;
\
CREATE USER dbaIntervention IDENTIFIED BY mdp DEFAULT TABLESPACE Intervention_tbs TEMPORARY TABLESPACE Intervention_temptbs;
\
GRANT ALL PRIVILEGES TO dbaIntervention;
\
CREATE TABLE CLIENT(
    NUMCLIENT INTEGER PRIMARY KEY, 
    CIV VARCHAR2(3) CHECK IN  ('M', 'Mle', 'Mme'), 
    PRENOMCLIENT VARCHAR2(40), 
    NOMCLIENT VARCHAR2(40), 
    DATENAISSANCE Date,  
    ADRESSE VARCHAR2(40), 
    TELPROF VARCHAR2(40), 
    TELPRIV VARCHAR2(40), 
    FAX VARCHAR2(40)
    );
\
CREATE TABLE EMPLOYE (
    NUMEMPLOYE INTEGER PRIMARY KEY, 
    NOMEMP VARCHAR2(40), 
    PRENOMEMP VARCHAR2(40), 
    CATEGORIE VARCHAR2(40) CHECK IN ('Mécanicien','Assitant'), 
    SALAIRE FLOAT
) 
\
CREATE TABLE MARQUE (
    NUMMARQUE INTEGER PRIMARY KEY, 
    MARQUE, 
    PAYS
    ) 
\ 
CREATE TABLE MODELE (
    NUMMODELE INTEGER PRIMARY KEY,
    NUMMARQUE INTEGER, 
    MODELE VARCHAR2(40),

    CONSTRAINT FK_numMarque FOREIGN KEY NUMMARQUE REFERENCES MARQUE(NUMMARQUE)
    ) 
\
CREATE TABLE VEHICULE (
    NUMVEHICULE INTEGER PRIMARY KEY, 
    NUMCLIENT INTEGER, 
    NUMMODELE INTEGER, 
    NUMIMMAT INTEGER, 
    ANNEE VARCHAR2(40),

    CONSTRAINT FK_numClient FOREIGN KEY NUMCLIENT REFERENCES CLIENT(NUMCLIENT),
    CONSTRAINT FK_numModele FOREIGN KEY NUMMODELE REFERENCES MODELE(NUMMODELE)
    ) 
\
CREATE TABLE INTERVENTIONS (
    NUMINTERVENTION INTEGER PRIMARY KEY, 
    NUMVEHICULE INTEGER, 
    TYPEINTERVENTION VARCHAR2(40), 
    DATEDEBINTERV Date, 
    DATEFININTERV Date,  
    COUTINTERV FLOAT,

    CONSTRAINT FK_numVehicule FOREIGN KEY NUMVEHICULE REFERENCES VEHICULE(NUMVEHICULE)
    ) 
\
CREATE TABLE INTERVENANTS (
    NUMINTERVENTION INTEGER, 
    NUMEMPLOYE INTEGER, 
    DATEDEBUT Date, 
    DATEFIN Date,

    CONSTRAINT FK_numIntervention FOREIGN KEY NUMINTERVENTION REFERENCES INTERVENTIONS(NUMINTERVENTION),
    CONSTRAINT FK_numEmploye FOREIGN KEY NUMEMPLOYE REFERENCES EMPLOYE(NUMEMPLOYE),
    CONSTRAINT PK_intervenants PRIMARY KEY (NUMINTERVENTION,NUMEMPLOYE)
    )